apiVersion: v1
data:
  tls.crt:
  tls.key:
kind: Secret
metadata:
  annotations:
    auth.openshift.io/certificate-hostnames: ovn
  labels:
    auth.openshift.io/managed-certificate-type: target
  name: ovn-cert
  namespace: openshift-ovn-kubernetes
type: kubernetes.io/tls
